# Generated by Django 4.2.5 on 2023-10-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='id_family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.toolsfamilymodel', verbose_name='Familia de herramientas'),
        ),
    ]
