# Generated by Django 4.2.5 on 2023-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_toolsmodel_brand_alter_toolsmodel_id_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxequipmentmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='freightmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='labourmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='materialsmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='subcontractjobmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='data_aditional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datos adicionales'),
        ),
    ]
