# Generated by Django 4.2.5 on 2023-10-09 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0003_alter_auxequipmentmodel_data_aditional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxequipmentmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='auxequipmentmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='freightmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='freightmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='labourmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='labourmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='materialsmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='materialsmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='subcontractjobmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='subcontractjobmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='id_user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que creó el insumo'),
        ),
    ]
