# Generated by Django 4.2.5 on 2023-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auxequipmentmodel_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxequipmentmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='freightmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='labourmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='materialsmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='subcontractjobmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='toolsmodel',
            name='cost',
        ),
        migrations.AlterField(
            model_name='labourmodel',
            name='fact_real_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Factor de salario real'),
        ),
    ]
