# Generated by Django 4.2.5 on 2023-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourrelarionshipmodel',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materialsrelationshipmodel',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Cantidad'),
        ),
    ]
