# Generated by Django 4.2.5 on 2023-10-09 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0004_auxequipmentmodel_cost_and_more'),
        ('APUs', '0002_alter_labourrelarionshipmodel_cant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisofunitarypricesmodel',
            options={'verbose_name': 'Analisis de Precios Unitarios APU', 'verbose_name_plural': 'Analisis de Precios Unitarios APU'},
        ),
        migrations.RemoveField(
            model_name='labourrelarionshipmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='materialsrelationshipmodel',
            name='cost',
        ),
        migrations.AlterField(
            model_name='labourrelarionshipmodel',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='labourrelarionshipmodel',
            name='id_user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo'),
        ),
        migrations.AlterField(
            model_name='materialsrelationshipmodel',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materialsrelationshipmodel',
            name='id_user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo'),
        ),
        migrations.CreateModel(
            name='ToolsRelarionshipModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación')),
                ('date_delete', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de eliminación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('id_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.toolsmodel', verbose_name='Herramienta')),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo')),
            ],
            options={
                'verbose_name': 'Relación herramientas - APU',
                'verbose_name_plural': 'Relaciones herramientas - APU',
            },
        ),
        migrations.CreateModel(
            name='SubcontractJobRelarionshipModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación')),
                ('date_delete', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de eliminación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('id_subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.subcontractjobmodel', verbose_name='Subcontrato')),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo')),
            ],
            options={
                'verbose_name': 'Relación subcontratos - APU',
                'verbose_name_plural': 'Relaciones subcontratos - APU',
            },
        ),
        migrations.CreateModel(
            name='FreightRelarionshipModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación')),
                ('date_delete', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de eliminación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('id_freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.freightmodel', verbose_name='Subcontrato')),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo')),
            ],
            options={
                'verbose_name': 'Relación fletes - APU',
                'verbose_name_plural': 'Relaciones fletes - APU',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRelarionshipModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación')),
                ('date_delete', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de eliminación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.equipmentmodel', verbose_name='Subcontrato')),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo')),
            ],
            options={
                'verbose_name': 'Relación equipos - APU',
                'verbose_name_plural': 'Relaciones equipos - APU',
            },
        ),
        migrations.CreateModel(
            name='AuxEquipmentRelarionshipModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación')),
                ('date_delete', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de eliminación')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.auxequipmentmodel', verbose_name='Subcontrato')),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario que añadió el insumo')),
            ],
            options={
                'verbose_name': 'Relación equipos auxiliares - APU',
                'verbose_name_plural': 'Relaciones equipos auxiliares - APU',
            },
        ),
    ]
