# Generated by Django 4.2.5 on 2023-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APUs', '0003_alter_analysisofunitarypricesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxequipmentrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='equipmentrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='freightrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='labourrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='materialsrelationshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='subcontractjobrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='toolsrelarionshipmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo total'),
        ),
    ]
